openapi: 3.0.0
info:
  title: Products API
  description: Products API allows access to HashiCoffee Coffees and Ingredients
  version: 0.1.9
servers:
  - url: http://localhost:9090
security:
  - APIKey: [ ]
externalDocs:
  url: https://docs.speakeasyapi.dev
  description: The Speakeasy Platform Documentation
tags:
  - name: Order
paths:
  /v1/order:
    post:
      summary: Create an order
      x-speakeasy-entity-operation: Order#create
      operationId: createOrder
      # parameters:
      #   - description: If this order is a draft (dry-run) order
      #     in: query
      #     name: draft
      #     required: true
      #     schema:
      #       type: boolean
      requestBody:
        description: A JSON representation of the order to upsert
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
          description: OK
      tags:
        - Order
  /v1/order/{orderID}:
    get:
      summary: Get an order
      x-speakeasy-entity-operation: Order#get
      operationId: getOrder
      parameters:
        - description: The ID of the order
          in: path
          name: orderID
          x-speakeasy-match: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
          description: OK
      tags:
        - Order
    put:
      summary: Update an order
      x-speakeasy-entity-operation: Order#update
      operationId: updateOrder
      parameters:
        - description: The ID of the order
          in: path
          name: orderID
          x-speakeasy-match: id
          required: true
          schema:
            type: integer
      requestBody:
        description: A JSON representation of the order to upsert
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
          description: OK
      tags:
        - Order

    delete:
      summary: Delete an order
      x-speakeasy-entity-operation: Order#delete
      operationId: deleteOrder
      parameters:
        - description: The ID of the order
          in: path
          name: orderID
          x-speakeasy-match: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
      tags:
        - Order
components:
  schemas:
    Coffee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        teaser:
          type: string
        collection:
          type: string
        origin:
          type: string
        color:
          type: string
        description:
          type: string
        price:
          type: number
        image:
          type: string
        ingredients:
          type: string
    Order:
      type: object
      description: "Order defines an order in the database"
      x-speakeasy-entity: Order
      properties:
        id:
          type: integer
        items:
          $ref: "#/components/schemas/OrderItems"
    OrderItems:
      type: array
      items:
        $ref: "#/components/schemas/OrderItem"
    OrderItem:
      type: object
      description: An OrderItem is an item/quantity in an order
      properties:
        id:
          type: integer
        order_id:
          type: integer
        coffee_id:
          type: integer
        coffee:
          $ref: "#/components/schemas/Coffee"
        quantity:
          type: integer
      required:
        - name
        - teaser
        - description
        - price
        - image
  securitySchemes:
    APIKey:
      description: The API Key for the workspace
      in: header
      name: x-api-key
      type: apiKey
