openapi: 3.0.3
info:
  description: Example Hashicups through Speakeasy
  title: Hashicups
  version: 0.0.1
servers:
  # docker run -p 35123:80 kennethreitz/httpbin
  - url: http://localhost:35123/anything
security:
  - APIKey: []
externalDocs:
  url: https://docs.speakeasyapi.dev
  description: The Speakeasy Platform Documentation
tags:
  - name: Order

paths:
  /v1/order:
    put:
      summary: Create an order
      x-speakeasy-entity-operation: Order#create,update
      operationId: upsertOrder
      requestBody:
        description: A JSON representation of the Api to upsert
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderInput"
        required: true
      responses:
        "200":
          description: OK
      tags:
        - Order
  /v1/order/{orderID}:
    delete:
      summary: Delete an order
      x-speakeasy-entity-operation: Order#delete
      operationId: deleteOrder
      parameters:
        - description: The ID of the order to delete.
          in: path
          name: orderID
          x-speakeasy-match: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
      tags:
        - Order
components:
  schemas:
    CreateOrderInput:
      description: An input object to creating an order
      x-speakeasy-entity: Order
      properties:
        id:
          type: integer
          description: Order ID
        name:
          type: string
          description: Product name of the coffee.
        teaser:
          type: string
          description: Fun tagline for the coffee.
        description:
          type: string
          description: Product description of the coffee.
        price:
          type: number
          description: Suggested cost of the coffee.
        image:
          type: string
          description: URI for an image of the coffee.
      required:
        - name
        - teaser
        - price
        - image
      type: object
  securitySchemes:
    APIKey:
      description: The API Key for the workspace
      in: header
      name: x-api-key
      type: apiKey
