// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Coffee struct {
	Collection  *string  `json:"collection,omitempty"`
	Color       *string  `json:"color,omitempty"`
	Description *string  `json:"description,omitempty"`
	ID          *int64   `json:"id,omitempty"`
	Image       *string  `json:"image,omitempty"`
	Ingredients *string  `json:"ingredients,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Origin      *string  `json:"origin,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Teaser      *string  `json:"teaser,omitempty"`
}
