// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateOrderInput - An input object to creating an order
type CreateOrderInput struct {
	// Product description of the coffee.
	Description *string `json:"description,omitempty"`
	// URI for an image of the coffee.
	Image string `json:"image"`
	// Product name of the coffee.
	Name string `json:"name"`
	// Suggested cost of the coffee.
	Price float64 `json:"price"`
	// Fun tagline for the coffee.
	Teaser string `json:"teaser"`
}
