// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateOrderInput - An input object to creating an order
type CreateOrderInput struct {
	// Product description of the coffee.
	Description *string `json:"description,omitempty"`
	// URI for an image of the coffee.
	Image string `json:"image"`
	// Product name of the coffee.
	Name string `json:"name"`
	// Suggested cost of the coffee.
	Price float64 `json:"price"`
	// Fun tagline for the coffee.
	Teaser string `json:"teaser"`
}

func (o *CreateOrderInput) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateOrderInput) GetImage() string {
	if o == nil {
		return ""
	}
	return o.Image
}

func (o *CreateOrderInput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateOrderInput) GetPrice() float64 {
	if o == nil {
		return 0.0
	}
	return o.Price
}

func (o *CreateOrderInput) GetTeaser() string {
	if o == nil {
		return ""
	}
	return o.Teaser
}
