// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Order - Order defines an order in the database
type Order struct {
	ID    *int64      `json:"id,omitempty"`
	Items []OrderItem `json:"items,omitempty"`
}
