// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Order - An order helps you make coffee
type Order struct {
	// Product description of the coffee.
	Description *string `json:"description,omitempty"`
	// Order ID
	ID int64 `json:"id"`
	// URI for an image of the coffee.
	Image string `json:"image"`
	// Product name of the coffee.
	Name string `json:"name"`
	// Suggested cost of the coffee.
	Price float64 `json:"price"`
	// Fun tagline for the coffee.
	Teaser string `json:"teaser"`
}

func (o *Order) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Order) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Order) GetImage() string {
	if o == nil {
		return ""
	}
	return o.Image
}

func (o *Order) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Order) GetPrice() float64 {
	if o == nil {
		return 0.0
	}
	return o.Price
}

func (o *Order) GetTeaser() string {
	if o == nil {
		return ""
	}
	return o.Teaser
}
