// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Order - An order helps you make coffee
type Order struct {
	// Product description of the coffee.
	Description *string `json:"description,omitempty"`
	// Order ID
	ID int64 `json:"id"`
	// URI for an image of the coffee.
	Image string `json:"image"`
	// Product name of the coffee.
	Name string `json:"name"`
	// Suggested cost of the coffee.
	Price float64 `json:"price"`
	// Fun tagline for the coffee.
	Teaser string `json:"teaser"`
}
