// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"hashicups/internal/sdk/pkg/models/shared"
	"math/big"
)

func (r *OrderResourceModel) ToSDKType() *shared.Order {
	description := r.Description.ValueString()
	id := new(int64)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueInt64()
	} else {
		id = nil
	}
	image := r.Image.ValueString()
	name := r.Name.ValueString()
	price, _ := r.Price.ValueBigFloat().Float64()
	teaser := r.Teaser.ValueString()
	out := shared.Order{
		Description: description,
		ID:          id,
		Image:       image,
		Name:        name,
		Price:       price,
		Teaser:      teaser,
	}
	return &out

}

func (r *OrderResourceModel) RefreshFromSDKType(resp *shared.Order) {
	r.Description = types.StringValue(resp.Description)
	if resp.ID != nil {
		r.ID = types.Int64Value(*resp.ID)
	} else {
		r.ID = types.Int64Null()
	}
	r.Image = types.StringValue(resp.Image)
	r.Name = types.StringValue(resp.Name)
	r.Price = types.NumberValue(big.NewFloat(resp.Price))
	r.Teaser = types.StringValue(resp.Teaser)

}
