// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"hashicups/internal/sdk/pkg/models/shared"
)

func (r *OrderResourceModel) ToCreateSDKType() *shared.CreateOrderInput {
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	id := new(int64)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueInt64()
	} else {
		id = nil
	}
	image := r.Image.ValueString()
	name := r.Name.ValueString()
	price, _ := r.Price.ValueBigFloat().Float64()
	teaser := r.Teaser.ValueString()
	out := shared.CreateOrderInput{
		Description: description,
		ID:          id,
		Image:       image,
		Name:        name,
		Price:       price,
		Teaser:      teaser,
	}
	return &out
}

func (r *OrderResourceModel) ToUpdateSDKType() *shared.CreateOrderInput {
	out := r.ToCreateSDKType()
	return out
}

func (r *OrderResourceModel) ToDeleteSDKType() *shared.CreateOrderInput {
	out := r.ToCreateSDKType()
	return out
}
