// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type OrderItem struct {
	Coffee   *Coffee     `tfsdk:"coffee"`
	CoffeeID types.Int64 `tfsdk:"coffee_id"`
	ID       types.Int64 `tfsdk:"id"`
	OrderID  types.Int64 `tfsdk:"order_id"`
	Quantity types.Int64 `tfsdk:"quantity"`
}
