// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Coffee struct {
	Collection  types.String `tfsdk:"collection"`
	Color       types.String `tfsdk:"color"`
	Description types.String `tfsdk:"description"`
	ID          types.Int64  `tfsdk:"id"`
	Image       types.String `tfsdk:"image"`
	Ingredients types.String `tfsdk:"ingredients"`
	Name        types.String `tfsdk:"name"`
	Origin      types.String `tfsdk:"origin"`
	Price       types.Number `tfsdk:"price"`
	Teaser      types.String `tfsdk:"teaser"`
}
