// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOrderRequest struct {
	// The ID of the order to delete.
	OrderID int64 `pathParam:"style=simple,explode=false,name=orderID"`
}

type DeleteOrderResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
