// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOrderRequest struct {
	// The ID of the order to delete.
	OrderID int64 `pathParam:"style=simple,explode=false,name=orderID"`
}

type DeleteOrderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
